language: objective-c
env:j
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -project SFSerialize.xcodeproj -scheme SFSerialize test | xcpretty -c
