language: objective-c
osx_image: beta-xcode6.3
script:
  - xcodebuild -project SFSerialize.xcodeproj -scheme SFSerialize -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" ONLY_ACTIVE_ARCH=NO test
